services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: nasa-pod-app_client
    env_file: .env
    environment:
      EXAMPLE: woof
    networks:
      - app-network
    ports:
      - "8080:8080"
      - "9229:9229"
    volumes:
      - ./client:/opt/nasa-pod-app/client
      - /opt/nasa-pod-app/node_modules

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: client-dev
    container_name: nasa-pod-app_server
    command: npm start
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      APP_ENV: ${APP_ENV}
      API_HOST: ${API_HOST}
      PORT: ${PORT}
      API_TOKEN: ${API_TOKEN}
      MONGO_HOST: ${MONGO_HOST}
    networks:
      - app-network

  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local
